/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WordCloudItemDto } from './WordCloudItemDto';
import {
    WordCloudItemDtoFromJSON,
    WordCloudItemDtoFromJSONTyped,
    WordCloudItemDtoToJSON,
    WordCloudItemDtoToJSONTyped,
} from './WordCloudItemDto';

/**
 * 관리자 사용자 워드클라우드 조회 결과
 * @export
 * @interface AdminUserWordCloudResponse
 */
export interface AdminUserWordCloudResponse {
    /**
     * 사용자 ID
     * @type {string}
     * @memberof AdminUserWordCloudResponse
     */
    userId: string;
    /**
     * 분석에 사용된 일기 개수
     * @type {number}
     * @memberof AdminUserWordCloudResponse
     */
    totalDiaries: number;
    /**
     * 전체 단어 총합
     * @type {number}
     * @memberof AdminUserWordCloudResponse
     */
    totalTokens: number;
    /**
     * 상위 단어 목록
     * @type {Array<WordCloudItemDto>}
     * @memberof AdminUserWordCloudResponse
     */
    items: Array<WordCloudItemDto>;
}

/**
 * Check if a given object implements the AdminUserWordCloudResponse interface.
 */
export function instanceOfAdminUserWordCloudResponse(value: object): value is AdminUserWordCloudResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('totalDiaries' in value) || value['totalDiaries'] === undefined) return false;
    if (!('totalTokens' in value) || value['totalTokens'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function AdminUserWordCloudResponseFromJSON(json: any): AdminUserWordCloudResponse {
    return AdminUserWordCloudResponseFromJSONTyped(json, false);
}

export function AdminUserWordCloudResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserWordCloudResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'totalDiaries': json['totalDiaries'],
        'totalTokens': json['totalTokens'],
        'items': ((json['items'] as Array<any>).map(WordCloudItemDtoFromJSON)),
    };
}

export function AdminUserWordCloudResponseToJSON(json: any): AdminUserWordCloudResponse {
    return AdminUserWordCloudResponseToJSONTyped(json, false);
}

export function AdminUserWordCloudResponseToJSONTyped(value?: AdminUserWordCloudResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'totalDiaries': value['totalDiaries'],
        'totalTokens': value['totalTokens'],
        'items': ((value['items'] as Array<any>).map(WordCloudItemDtoToJSON)),
    };
}

