/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiaryWelfareServiceDto } from './DiaryWelfareServiceDto';
import {
    DiaryWelfareServiceDtoFromJSON,
    DiaryWelfareServiceDtoFromJSONTyped,
    DiaryWelfareServiceDtoToJSON,
    DiaryWelfareServiceDtoToJSONTyped,
} from './DiaryWelfareServiceDto';

/**
 * 관리자 일기 복지 서비스 조회 응답
 * @export
 * @interface AdminDiaryWelfareServiceResponse
 */
export interface AdminDiaryWelfareServiceResponse {
    /**
     * 일기 ID
     * @type {string}
     * @memberof AdminDiaryWelfareServiceResponse
     */
    diaryId: string;
    /**
     * 매칭된 복지 서비스 목록
     * @type {Array<DiaryWelfareServiceDto>}
     * @memberof AdminDiaryWelfareServiceResponse
     */
    welfareServices: Array<DiaryWelfareServiceDto>;
}

/**
 * Check if a given object implements the AdminDiaryWelfareServiceResponse interface.
 */
export function instanceOfAdminDiaryWelfareServiceResponse(value: object): value is AdminDiaryWelfareServiceResponse {
    if (!('diaryId' in value) || value['diaryId'] === undefined) return false;
    if (!('welfareServices' in value) || value['welfareServices'] === undefined) return false;
    return true;
}

export function AdminDiaryWelfareServiceResponseFromJSON(json: any): AdminDiaryWelfareServiceResponse {
    return AdminDiaryWelfareServiceResponseFromJSONTyped(json, false);
}

export function AdminDiaryWelfareServiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDiaryWelfareServiceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'diaryId': json['diaryId'],
        'welfareServices': ((json['welfareServices'] as Array<any>).map(DiaryWelfareServiceDtoFromJSON)),
    };
}

export function AdminDiaryWelfareServiceResponseToJSON(json: any): AdminDiaryWelfareServiceResponse {
    return AdminDiaryWelfareServiceResponseToJSONTyped(json, false);
}

export function AdminDiaryWelfareServiceResponseToJSONTyped(value?: AdminDiaryWelfareServiceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'diaryId': value['diaryId'],
        'welfareServices': ((value['welfareServices'] as Array<any>).map(DiaryWelfareServiceDtoToJSON)),
    };
}

