/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 관리자 사용자 상세 조회 응답
 * @export
 * @interface AdminUserDetailResponse
 */
export interface AdminUserDetailResponse {
    /**
     * 사용자 ID
     * @type {string}
     * @memberof AdminUserDetailResponse
     */
    userId: string;
    /**
     * 이름
     * @type {string}
     * @memberof AdminUserDetailResponse
     */
    name: string;
    /**
     * 생년월일
     * @type {Date}
     * @memberof AdminUserDetailResponse
     */
    birthDate: Date;
    /**
     * 주 진단명
     * @type {string}
     * @memberof AdminUserDetailResponse
     */
    primaryDiagnosis?: string;
    /**
     * 일기 작성 날짜 목록
     * @type {Array<Date>}
     * @memberof AdminUserDetailResponse
     */
    diaryDates: Array<Date>;
    /**
     * 이번 달 작성한 일기 수
     * @type {number}
     * @memberof AdminUserDetailResponse
     */
    monthlyDiaryCount: number;
    /**
     * 올해 작성한 일기 수
     * @type {number}
     * @memberof AdminUserDetailResponse
     */
    yearlyDiaryCount: number;
    /**
     * 감정별 일기 수 (HAPPY, LOVE, SAD)
     * @type {{ [key: string]: number; }}
     * @memberof AdminUserDetailResponse
     */
    emotionCounts: { [key: string]: number; };
    /**
     * 위험 평가 사유
     * @type {string}
     * @memberof AdminUserDetailResponse
     */
    riskReason?: string;
}

/**
 * Check if a given object implements the AdminUserDetailResponse interface.
 */
export function instanceOfAdminUserDetailResponse(value: object): value is AdminUserDetailResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('birthDate' in value) || value['birthDate'] === undefined) return false;
    if (!('diaryDates' in value) || value['diaryDates'] === undefined) return false;
    if (!('monthlyDiaryCount' in value) || value['monthlyDiaryCount'] === undefined) return false;
    if (!('yearlyDiaryCount' in value) || value['yearlyDiaryCount'] === undefined) return false;
    if (!('emotionCounts' in value) || value['emotionCounts'] === undefined) return false;
    return true;
}

export function AdminUserDetailResponseFromJSON(json: any): AdminUserDetailResponse {
    return AdminUserDetailResponseFromJSONTyped(json, false);
}

export function AdminUserDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'name': json['name'],
        'birthDate': (new Date(json['birthDate'])),
        'primaryDiagnosis': json['primaryDiagnosis'] == null ? undefined : json['primaryDiagnosis'],
        'diaryDates': json['diaryDates'],
        'monthlyDiaryCount': json['monthlyDiaryCount'],
        'yearlyDiaryCount': json['yearlyDiaryCount'],
        'emotionCounts': json['emotionCounts'],
        'riskReason': json['riskReason'] == null ? undefined : json['riskReason'],
    };
}

export function AdminUserDetailResponseToJSON(json: any): AdminUserDetailResponse {
    return AdminUserDetailResponseToJSONTyped(json, false);
}

export function AdminUserDetailResponseToJSONTyped(value?: AdminUserDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'name': value['name'],
        'birthDate': value['birthDate'].toISOString().substring(0,10),
        'primaryDiagnosis': value['primaryDiagnosis'],
        'diaryDates': value['diaryDates'],
        'monthlyDiaryCount': value['monthlyDiaryCount'],
        'yearlyDiaryCount': value['yearlyDiaryCount'],
        'emotionCounts': value['emotionCounts'],
        'riskReason': value['riskReason'],
    };
}

