/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminUserDto } from './AdminUserDto';
import {
    AdminUserDtoFromJSON,
    AdminUserDtoFromJSONTyped,
    AdminUserDtoToJSON,
    AdminUserDtoToJSONTyped,
} from './AdminUserDto';

/**
 * 관리자 전체 사용자 목록 조회 응답
 * @export
 * @interface AdminUserFindAllResponse
 */
export interface AdminUserFindAllResponse {
    /**
     * 사용자 목록
     * @type {Array<AdminUserDto>}
     * @memberof AdminUserFindAllResponse
     */
    users: Array<AdminUserDto>;
}

/**
 * Check if a given object implements the AdminUserFindAllResponse interface.
 */
export function instanceOfAdminUserFindAllResponse(value: object): value is AdminUserFindAllResponse {
    if (!('users' in value) || value['users'] === undefined) return false;
    return true;
}

export function AdminUserFindAllResponseFromJSON(json: any): AdminUserFindAllResponse {
    return AdminUserFindAllResponseFromJSONTyped(json, false);
}

export function AdminUserFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'users': ((json['users'] as Array<any>).map(AdminUserDtoFromJSON)),
    };
}

export function AdminUserFindAllResponseToJSON(json: any): AdminUserFindAllResponse {
    return AdminUserFindAllResponseToJSONTyped(json, false);
}

export function AdminUserFindAllResponseToJSONTyped(value?: AdminUserFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': ((value['users'] as Array<any>).map(AdminUserDtoToJSON)),
    };
}

