/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScaleQuestionResultDto } from './ScaleQuestionResultDto';
import {
    ScaleQuestionResultDtoFromJSON,
    ScaleQuestionResultDtoFromJSONTyped,
    ScaleQuestionResultDtoToJSON,
    ScaleQuestionResultDtoToJSONTyped,
} from './ScaleQuestionResultDto';

/**
 * 관리자 사용자 척도 질문 응답 조회 결과
 * @export
 * @interface AdminUserScaleQuestionResultResponse
 */
export interface AdminUserScaleQuestionResultResponse {
    /**
     * 사용자 ID
     * @type {string}
     * @memberof AdminUserScaleQuestionResultResponse
     */
    userId: string;
    /**
     * 이름
     * @type {string}
     * @memberof AdminUserScaleQuestionResultResponse
     */
    name: string;
    /**
     * 생년월일
     * @type {Date}
     * @memberof AdminUserScaleQuestionResultResponse
     */
    birthDate: Date;
    /**
     * 주 진단명
     * @type {string}
     * @memberof AdminUserScaleQuestionResultResponse
     */
    primaryDiagnosis?: string;
    /**
     * 척도 질문 응답 회차
     * @type {number}
     * @memberof AdminUserScaleQuestionResultResponse
     */
    scaleQuestionTermCount: number;
    /**
     * 척도 카테고리별 질문 응답 결과 (키: ANXIETY_DEPRESSION/ANGER)
     * @type {{ [key: string]: ScaleQuestionResultDto; }}
     * @memberof AdminUserScaleQuestionResultResponse
     */
    items: { [key: string]: ScaleQuestionResultDto; };
}

/**
 * Check if a given object implements the AdminUserScaleQuestionResultResponse interface.
 */
export function instanceOfAdminUserScaleQuestionResultResponse(value: object): value is AdminUserScaleQuestionResultResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('birthDate' in value) || value['birthDate'] === undefined) return false;
    if (!('scaleQuestionTermCount' in value) || value['scaleQuestionTermCount'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function AdminUserScaleQuestionResultResponseFromJSON(json: any): AdminUserScaleQuestionResultResponse {
    return AdminUserScaleQuestionResultResponseFromJSONTyped(json, false);
}

export function AdminUserScaleQuestionResultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserScaleQuestionResultResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'name': json['name'],
        'birthDate': (new Date(json['birthDate'])),
        'primaryDiagnosis': json['primaryDiagnosis'] == null ? undefined : json['primaryDiagnosis'],
        'scaleQuestionTermCount': json['scaleQuestionTermCount'],
        'items': (mapValues(json['items'], ScaleQuestionResultDtoFromJSON)),
    };
}

export function AdminUserScaleQuestionResultResponseToJSON(json: any): AdminUserScaleQuestionResultResponse {
    return AdminUserScaleQuestionResultResponseToJSONTyped(json, false);
}

export function AdminUserScaleQuestionResultResponseToJSONTyped(value?: AdminUserScaleQuestionResultResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'name': value['name'],
        'birthDate': value['birthDate'].toISOString().substring(0,10),
        'primaryDiagnosis': value['primaryDiagnosis'],
        'scaleQuestionTermCount': value['scaleQuestionTermCount'],
        'items': (mapValues(value['items'], ScaleQuestionResultDtoToJSON)),
    };
}

