/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiaryKeywordDto } from './DiaryKeywordDto';
import {
    DiaryKeywordDtoFromJSON,
    DiaryKeywordDtoFromJSONTyped,
    DiaryKeywordDtoToJSON,
    DiaryKeywordDtoToJSONTyped,
} from './DiaryKeywordDto';

/**
 * 관리자 일기 키워드 조회 응답
 * @export
 * @interface AdminDiaryKeywordResponse
 */
export interface AdminDiaryKeywordResponse {
    /**
     * 일기 ID
     * @type {string}
     * @memberof AdminDiaryKeywordResponse
     */
    diaryId: string;
    /**
     * 추출된 키워드 목록
     * @type {Array<DiaryKeywordDto>}
     * @memberof AdminDiaryKeywordResponse
     */
    keywords: Array<DiaryKeywordDto>;
}

/**
 * Check if a given object implements the AdminDiaryKeywordResponse interface.
 */
export function instanceOfAdminDiaryKeywordResponse(value: object): value is AdminDiaryKeywordResponse {
    if (!('diaryId' in value) || value['diaryId'] === undefined) return false;
    if (!('keywords' in value) || value['keywords'] === undefined) return false;
    return true;
}

export function AdminDiaryKeywordResponseFromJSON(json: any): AdminDiaryKeywordResponse {
    return AdminDiaryKeywordResponseFromJSONTyped(json, false);
}

export function AdminDiaryKeywordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDiaryKeywordResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'diaryId': json['diaryId'],
        'keywords': ((json['keywords'] as Array<any>).map(DiaryKeywordDtoFromJSON)),
    };
}

export function AdminDiaryKeywordResponseToJSON(json: any): AdminDiaryKeywordResponse {
    return AdminDiaryKeywordResponseToJSONTyped(json, false);
}

export function AdminDiaryKeywordResponseToJSONTyped(value?: AdminDiaryKeywordResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'diaryId': value['diaryId'],
        'keywords': ((value['keywords'] as Array<any>).map(DiaryKeywordDtoToJSON)),
    };
}

