/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiarySdohItemDto } from './DiarySdohItemDto';
import {
    DiarySdohItemDtoFromJSON,
    DiarySdohItemDtoFromJSONTyped,
    DiarySdohItemDtoToJSON,
    DiarySdohItemDtoToJSONTyped,
} from './DiarySdohItemDto';

/**
 * 관리자 일기 SDOH 조회 응답
 * @export
 * @interface AdminDiarySdohResponse
 */
export interface AdminDiarySdohResponse {
    /**
     * SDOH 항목 목록
     * @type {Array<DiarySdohItemDto>}
     * @memberof AdminDiarySdohResponse
     */
    items: Array<DiarySdohItemDto>;
}

/**
 * Check if a given object implements the AdminDiarySdohResponse interface.
 */
export function instanceOfAdminDiarySdohResponse(value: object): value is AdminDiarySdohResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function AdminDiarySdohResponseFromJSON(json: any): AdminDiarySdohResponse {
    return AdminDiarySdohResponseFromJSONTyped(json, false);
}

export function AdminDiarySdohResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminDiarySdohResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(DiarySdohItemDtoFromJSON)),
    };
}

export function AdminDiarySdohResponseToJSON(json: any): AdminDiarySdohResponse {
    return AdminDiarySdohResponseToJSONTyped(json, false);
}

export function AdminDiarySdohResponseToJSONTyped(value?: AdminDiarySdohResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(DiarySdohItemDtoToJSON)),
    };
}

