/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserScaleItem } from './UserScaleItem';
import {
    UserScaleItemFromJSON,
    UserScaleItemFromJSONTyped,
    UserScaleItemToJSON,
    UserScaleItemToJSONTyped,
} from './UserScaleItem';

/**
 * 관리자 사용자 척도 결과 조회 응답
 * @export
 * @interface AdminUserScaleFindAllResponse
 */
export interface AdminUserScaleFindAllResponse {
    /**
     * 회차별 척도 결과 (키: 회차 번호, 값: 해당 회차의 척도 점수 목록)
     * @type {{ [key: string]: Array<UserScaleItem>; }}
     * @memberof AdminUserScaleFindAllResponse
     */
    items: { [key: string]: Array<UserScaleItem>; };
}

/**
 * Check if a given object implements the AdminUserScaleFindAllResponse interface.
 */
export function instanceOfAdminUserScaleFindAllResponse(value: object): value is AdminUserScaleFindAllResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function AdminUserScaleFindAllResponseFromJSON(json: any): AdminUserScaleFindAllResponse {
    return AdminUserScaleFindAllResponseFromJSONTyped(json, false);
}

export function AdminUserScaleFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUserScaleFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'],
    };
}

export function AdminUserScaleFindAllResponseToJSON(json: any): AdminUserScaleFindAllResponse {
    return AdminUserScaleFindAllResponseToJSONTyped(json, false);
}

export function AdminUserScaleFindAllResponseToJSONTyped(value?: AdminUserScaleFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'],
    };
}

