/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CareManagerResponse } from './CareManagerResponse';
import {
    CareManagerResponseFromJSON,
    CareManagerResponseFromJSONTyped,
    CareManagerResponseToJSON,
    CareManagerResponseToJSONTyped,
} from './CareManagerResponse';

/**
 * 담당 관리자 목록 응답
 * @export
 * @interface CareManagerFindAllResponse
 */
export interface CareManagerFindAllResponse {
    /**
     * 담당 관리자 목록
     * @type {Array<CareManagerResponse>}
     * @memberof CareManagerFindAllResponse
     */
    careManagers: Array<CareManagerResponse>;
}

/**
 * Check if a given object implements the CareManagerFindAllResponse interface.
 */
export function instanceOfCareManagerFindAllResponse(value: object): value is CareManagerFindAllResponse {
    if (!('careManagers' in value) || value['careManagers'] === undefined) return false;
    return true;
}

export function CareManagerFindAllResponseFromJSON(json: any): CareManagerFindAllResponse {
    return CareManagerFindAllResponseFromJSONTyped(json, false);
}

export function CareManagerFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'careManagers': ((json['careManagers'] as Array<any>).map(CareManagerResponseFromJSON)),
    };
}

export function CareManagerFindAllResponseToJSON(json: any): CareManagerFindAllResponse {
    return CareManagerFindAllResponseToJSONTyped(json, false);
}

export function CareManagerFindAllResponseToJSONTyped(value?: CareManagerFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'careManagers': ((value['careManagers'] as Array<any>).map(CareManagerResponseToJSON)),
    };
}

