/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareManagerResponse
 */
export interface CareManagerResponse {
    /**
     * 
     * @type {string}
     * @memberof CareManagerResponse
     */
    managerId: string;
    /**
     * 
     * @type {string}
     * @memberof CareManagerResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CareManagerResponse
     */
    email: string;
}

/**
 * Check if a given object implements the CareManagerResponse interface.
 */
export function instanceOfCareManagerResponse(value: object): value is CareManagerResponse {
    if (!('managerId' in value) || value['managerId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function CareManagerResponseFromJSON(json: any): CareManagerResponse {
    return CareManagerResponseFromJSONTyped(json, false);
}

export function CareManagerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareManagerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'managerId': json['managerId'],
        'name': json['name'],
        'email': json['email'],
    };
}

export function CareManagerResponseToJSON(json: any): CareManagerResponse {
    return CareManagerResponseToJSONTyped(json, false);
}

export function CareManagerResponseToJSONTyped(value?: CareManagerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'managerId': value['managerId'],
        'name': value['name'],
        'email': value['email'],
    };
}

