/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminUserDetailResponse } from './AdminUserDetailResponse';
import {
    AdminUserDetailResponseFromJSON,
    AdminUserDetailResponseFromJSONTyped,
    AdminUserDetailResponseToJSON,
    AdminUserDetailResponseToJSONTyped,
} from './AdminUserDetailResponse';

/**
 * 
 * @export
 * @interface CommonResponseAdminUserDetailResponse
 */
export interface CommonResponseAdminUserDetailResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseAdminUserDetailResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminUserDetailResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminUserDetailResponse
     */
    message: string;
    /**
     * 
     * @type {AdminUserDetailResponse}
     * @memberof CommonResponseAdminUserDetailResponse
     */
    data?: AdminUserDetailResponse;
}

/**
 * Check if a given object implements the CommonResponseAdminUserDetailResponse interface.
 */
export function instanceOfCommonResponseAdminUserDetailResponse(value: object): value is CommonResponseAdminUserDetailResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseAdminUserDetailResponseFromJSON(json: any): CommonResponseAdminUserDetailResponse {
    return CommonResponseAdminUserDetailResponseFromJSONTyped(json, false);
}

export function CommonResponseAdminUserDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseAdminUserDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : AdminUserDetailResponseFromJSON(json['data']),
    };
}

export function CommonResponseAdminUserDetailResponseToJSON(json: any): CommonResponseAdminUserDetailResponse {
    return CommonResponseAdminUserDetailResponseToJSONTyped(json, false);
}

export function CommonResponseAdminUserDetailResponseToJSONTyped(value?: CommonResponseAdminUserDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': AdminUserDetailResponseToJSON(value['data']),
    };
}

