/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminUserScaleQuestionResultResponse } from './AdminUserScaleQuestionResultResponse';
import {
    AdminUserScaleQuestionResultResponseFromJSON,
    AdminUserScaleQuestionResultResponseFromJSONTyped,
    AdminUserScaleQuestionResultResponseToJSON,
    AdminUserScaleQuestionResultResponseToJSONTyped,
} from './AdminUserScaleQuestionResultResponse';

/**
 * 
 * @export
 * @interface CommonResponseAdminUserScaleQuestionResultResponse
 */
export interface CommonResponseAdminUserScaleQuestionResultResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseAdminUserScaleQuestionResultResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminUserScaleQuestionResultResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminUserScaleQuestionResultResponse
     */
    message: string;
    /**
     * 
     * @type {AdminUserScaleQuestionResultResponse}
     * @memberof CommonResponseAdminUserScaleQuestionResultResponse
     */
    data?: AdminUserScaleQuestionResultResponse;
}

/**
 * Check if a given object implements the CommonResponseAdminUserScaleQuestionResultResponse interface.
 */
export function instanceOfCommonResponseAdminUserScaleQuestionResultResponse(value: object): value is CommonResponseAdminUserScaleQuestionResultResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseAdminUserScaleQuestionResultResponseFromJSON(json: any): CommonResponseAdminUserScaleQuestionResultResponse {
    return CommonResponseAdminUserScaleQuestionResultResponseFromJSONTyped(json, false);
}

export function CommonResponseAdminUserScaleQuestionResultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseAdminUserScaleQuestionResultResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : AdminUserScaleQuestionResultResponseFromJSON(json['data']),
    };
}

export function CommonResponseAdminUserScaleQuestionResultResponseToJSON(json: any): CommonResponseAdminUserScaleQuestionResultResponse {
    return CommonResponseAdminUserScaleQuestionResultResponseToJSONTyped(json, false);
}

export function CommonResponseAdminUserScaleQuestionResultResponseToJSONTyped(value?: CommonResponseAdminUserScaleQuestionResultResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': AdminUserScaleQuestionResultResponseToJSON(value['data']),
    };
}

