/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminUserScaleFindAllResponse } from './AdminUserScaleFindAllResponse';
import {
    AdminUserScaleFindAllResponseFromJSON,
    AdminUserScaleFindAllResponseFromJSONTyped,
    AdminUserScaleFindAllResponseToJSON,
    AdminUserScaleFindAllResponseToJSONTyped,
} from './AdminUserScaleFindAllResponse';

/**
 * 
 * @export
 * @interface CommonResponseAdminUserScaleFindAllResponse
 */
export interface CommonResponseAdminUserScaleFindAllResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseAdminUserScaleFindAllResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminUserScaleFindAllResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminUserScaleFindAllResponse
     */
    message: string;
    /**
     * 
     * @type {AdminUserScaleFindAllResponse}
     * @memberof CommonResponseAdminUserScaleFindAllResponse
     */
    data?: AdminUserScaleFindAllResponse;
}

/**
 * Check if a given object implements the CommonResponseAdminUserScaleFindAllResponse interface.
 */
export function instanceOfCommonResponseAdminUserScaleFindAllResponse(value: object): value is CommonResponseAdminUserScaleFindAllResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseAdminUserScaleFindAllResponseFromJSON(json: any): CommonResponseAdminUserScaleFindAllResponse {
    return CommonResponseAdminUserScaleFindAllResponseFromJSONTyped(json, false);
}

export function CommonResponseAdminUserScaleFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseAdminUserScaleFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : AdminUserScaleFindAllResponseFromJSON(json['data']),
    };
}

export function CommonResponseAdminUserScaleFindAllResponseToJSON(json: any): CommonResponseAdminUserScaleFindAllResponse {
    return CommonResponseAdminUserScaleFindAllResponseToJSONTyped(json, false);
}

export function CommonResponseAdminUserScaleFindAllResponseToJSONTyped(value?: CommonResponseAdminUserScaleFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': AdminUserScaleFindAllResponseToJSON(value['data']),
    };
}

