/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminDiaryKeywordResponse } from './AdminDiaryKeywordResponse';
import {
    AdminDiaryKeywordResponseFromJSON,
    AdminDiaryKeywordResponseFromJSONTyped,
    AdminDiaryKeywordResponseToJSON,
    AdminDiaryKeywordResponseToJSONTyped,
} from './AdminDiaryKeywordResponse';

/**
 * 
 * @export
 * @interface CommonResponseAdminDiaryKeywordResponse
 */
export interface CommonResponseAdminDiaryKeywordResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseAdminDiaryKeywordResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminDiaryKeywordResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminDiaryKeywordResponse
     */
    message: string;
    /**
     * 
     * @type {AdminDiaryKeywordResponse}
     * @memberof CommonResponseAdminDiaryKeywordResponse
     */
    data?: AdminDiaryKeywordResponse;
}

/**
 * Check if a given object implements the CommonResponseAdminDiaryKeywordResponse interface.
 */
export function instanceOfCommonResponseAdminDiaryKeywordResponse(value: object): value is CommonResponseAdminDiaryKeywordResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseAdminDiaryKeywordResponseFromJSON(json: any): CommonResponseAdminDiaryKeywordResponse {
    return CommonResponseAdminDiaryKeywordResponseFromJSONTyped(json, false);
}

export function CommonResponseAdminDiaryKeywordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseAdminDiaryKeywordResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : AdminDiaryKeywordResponseFromJSON(json['data']),
    };
}

export function CommonResponseAdminDiaryKeywordResponseToJSON(json: any): CommonResponseAdminDiaryKeywordResponse {
    return CommonResponseAdminDiaryKeywordResponseToJSONTyped(json, false);
}

export function CommonResponseAdminDiaryKeywordResponseToJSONTyped(value?: CommonResponseAdminDiaryKeywordResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': AdminDiaryKeywordResponseToJSON(value['data']),
    };
}

