/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminUserFindAllResponse } from './AdminUserFindAllResponse';
import {
    AdminUserFindAllResponseFromJSON,
    AdminUserFindAllResponseFromJSONTyped,
    AdminUserFindAllResponseToJSON,
    AdminUserFindAllResponseToJSONTyped,
} from './AdminUserFindAllResponse';

/**
 * 
 * @export
 * @interface CommonResponseAdminUserFindAllResponse
 */
export interface CommonResponseAdminUserFindAllResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseAdminUserFindAllResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminUserFindAllResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminUserFindAllResponse
     */
    message: string;
    /**
     * 
     * @type {AdminUserFindAllResponse}
     * @memberof CommonResponseAdminUserFindAllResponse
     */
    data?: AdminUserFindAllResponse;
}

/**
 * Check if a given object implements the CommonResponseAdminUserFindAllResponse interface.
 */
export function instanceOfCommonResponseAdminUserFindAllResponse(value: object): value is CommonResponseAdminUserFindAllResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseAdminUserFindAllResponseFromJSON(json: any): CommonResponseAdminUserFindAllResponse {
    return CommonResponseAdminUserFindAllResponseFromJSONTyped(json, false);
}

export function CommonResponseAdminUserFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseAdminUserFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : AdminUserFindAllResponseFromJSON(json['data']),
    };
}

export function CommonResponseAdminUserFindAllResponseToJSON(json: any): CommonResponseAdminUserFindAllResponse {
    return CommonResponseAdminUserFindAllResponseToJSONTyped(json, false);
}

export function CommonResponseAdminUserFindAllResponseToJSONTyped(value?: CommonResponseAdminUserFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': AdminUserFindAllResponseToJSON(value['data']),
    };
}

