/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminUserWordCloudResponse } from './AdminUserWordCloudResponse';
import {
    AdminUserWordCloudResponseFromJSON,
    AdminUserWordCloudResponseFromJSONTyped,
    AdminUserWordCloudResponseToJSON,
    AdminUserWordCloudResponseToJSONTyped,
} from './AdminUserWordCloudResponse';

/**
 * 
 * @export
 * @interface CommonResponseAdminUserWordCloudResponse
 */
export interface CommonResponseAdminUserWordCloudResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseAdminUserWordCloudResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminUserWordCloudResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminUserWordCloudResponse
     */
    message: string;
    /**
     * 
     * @type {AdminUserWordCloudResponse}
     * @memberof CommonResponseAdminUserWordCloudResponse
     */
    data?: AdminUserWordCloudResponse;
}

/**
 * Check if a given object implements the CommonResponseAdminUserWordCloudResponse interface.
 */
export function instanceOfCommonResponseAdminUserWordCloudResponse(value: object): value is CommonResponseAdminUserWordCloudResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseAdminUserWordCloudResponseFromJSON(json: any): CommonResponseAdminUserWordCloudResponse {
    return CommonResponseAdminUserWordCloudResponseFromJSONTyped(json, false);
}

export function CommonResponseAdminUserWordCloudResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseAdminUserWordCloudResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : AdminUserWordCloudResponseFromJSON(json['data']),
    };
}

export function CommonResponseAdminUserWordCloudResponseToJSON(json: any): CommonResponseAdminUserWordCloudResponse {
    return CommonResponseAdminUserWordCloudResponseToJSONTyped(json, false);
}

export function CommonResponseAdminUserWordCloudResponseToJSONTyped(value?: CommonResponseAdminUserWordCloudResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': AdminUserWordCloudResponseToJSON(value['data']),
    };
}

