/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminDiaryWelfareServiceResponse } from './AdminDiaryWelfareServiceResponse';
import {
    AdminDiaryWelfareServiceResponseFromJSON,
    AdminDiaryWelfareServiceResponseFromJSONTyped,
    AdminDiaryWelfareServiceResponseToJSON,
    AdminDiaryWelfareServiceResponseToJSONTyped,
} from './AdminDiaryWelfareServiceResponse';

/**
 * 
 * @export
 * @interface CommonResponseAdminDiaryWelfareServiceResponse
 */
export interface CommonResponseAdminDiaryWelfareServiceResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseAdminDiaryWelfareServiceResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminDiaryWelfareServiceResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAdminDiaryWelfareServiceResponse
     */
    message: string;
    /**
     * 
     * @type {AdminDiaryWelfareServiceResponse}
     * @memberof CommonResponseAdminDiaryWelfareServiceResponse
     */
    data?: AdminDiaryWelfareServiceResponse;
}

/**
 * Check if a given object implements the CommonResponseAdminDiaryWelfareServiceResponse interface.
 */
export function instanceOfCommonResponseAdminDiaryWelfareServiceResponse(value: object): value is CommonResponseAdminDiaryWelfareServiceResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseAdminDiaryWelfareServiceResponseFromJSON(json: any): CommonResponseAdminDiaryWelfareServiceResponse {
    return CommonResponseAdminDiaryWelfareServiceResponseFromJSONTyped(json, false);
}

export function CommonResponseAdminDiaryWelfareServiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseAdminDiaryWelfareServiceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : AdminDiaryWelfareServiceResponseFromJSON(json['data']),
    };
}

export function CommonResponseAdminDiaryWelfareServiceResponseToJSON(json: any): CommonResponseAdminDiaryWelfareServiceResponse {
    return CommonResponseAdminDiaryWelfareServiceResponseToJSONTyped(json, false);
}

export function CommonResponseAdminDiaryWelfareServiceResponseToJSONTyped(value?: CommonResponseAdminDiaryWelfareServiceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': AdminDiaryWelfareServiceResponseToJSON(value['data']),
    };
}

