/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CareManagerFindAllResponse } from './CareManagerFindAllResponse';
import {
    CareManagerFindAllResponseFromJSON,
    CareManagerFindAllResponseFromJSONTyped,
    CareManagerFindAllResponseToJSON,
    CareManagerFindAllResponseToJSONTyped,
} from './CareManagerFindAllResponse';

/**
 * 
 * @export
 * @interface CommonResponseCareManagerFindAllResponse
 */
export interface CommonResponseCareManagerFindAllResponse {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseCareManagerFindAllResponse
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseCareManagerFindAllResponse
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseCareManagerFindAllResponse
     */
    message: string;
    /**
     * 
     * @type {CareManagerFindAllResponse}
     * @memberof CommonResponseCareManagerFindAllResponse
     */
    data?: CareManagerFindAllResponse;
}

/**
 * Check if a given object implements the CommonResponseCareManagerFindAllResponse interface.
 */
export function instanceOfCommonResponseCareManagerFindAllResponse(value: object): value is CommonResponseCareManagerFindAllResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseCareManagerFindAllResponseFromJSON(json: any): CommonResponseCareManagerFindAllResponse {
    return CommonResponseCareManagerFindAllResponseFromJSONTyped(json, false);
}

export function CommonResponseCareManagerFindAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseCareManagerFindAllResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'code': json['code'],
        'message': json['message'],
        'data': json['data'] == null ? undefined : CareManagerFindAllResponseFromJSON(json['data']),
    };
}

export function CommonResponseCareManagerFindAllResponseToJSON(json: any): CommonResponseCareManagerFindAllResponse {
    return CommonResponseCareManagerFindAllResponseToJSONTyped(json, false);
}

export function CommonResponseCareManagerFindAllResponseToJSONTyped(value?: CommonResponseCareManagerFindAllResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'code': value['code'],
        'message': value['message'],
        'data': CareManagerFindAllResponseToJSON(value['data']),
    };
}

