/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 일기 SDOH 항목 정보
 * @export
 * @interface DiarySdohItemDto
 */
export interface DiarySdohItemDto {
    /**
     * 요소 번호
     * @type {number}
     * @memberof DiarySdohItemDto
     */
    elementNo: number;
    /**
     * 대분류
     * @type {string}
     * @memberof DiarySdohItemDto
     */
    majorCat?: string;
    /**
     * 중분류
     * @type {string}
     * @memberof DiarySdohItemDto
     */
    middleCat?: string;
    /**
     * 소분류
     * @type {string}
     * @memberof DiarySdohItemDto
     */
    subCat?: string;
    /**
     * 징후 코드
     * @type {string}
     * @memberof DiarySdohItemDto
     */
    signCode?: string;
    /**
     * 유형 라벨
     * @type {string}
     * @memberof DiarySdohItemDto
     */
    typeLabel?: string;
    /**
     * 심각도 (1-5)
     * @type {number}
     * @memberof DiarySdohItemDto
     */
    severity?: number;
    /**
     * 지속 기간 (1-5)
     * @type {number}
     * @memberof DiarySdohItemDto
     */
    duration?: number;
    /**
     * 대처 능력 (1-5)
     * @type {number}
     * @memberof DiarySdohItemDto
     */
    coping?: number;
    /**
     * 권장 사항
     * @type {string}
     * @memberof DiarySdohItemDto
     */
    recommendation?: string;
    /**
     * 근거 문장 목록
     * @type {Array<string>}
     * @memberof DiarySdohItemDto
     */
    evidences: Array<string>;
}

/**
 * Check if a given object implements the DiarySdohItemDto interface.
 */
export function instanceOfDiarySdohItemDto(value: object): value is DiarySdohItemDto {
    if (!('elementNo' in value) || value['elementNo'] === undefined) return false;
    if (!('evidences' in value) || value['evidences'] === undefined) return false;
    return true;
}

export function DiarySdohItemDtoFromJSON(json: any): DiarySdohItemDto {
    return DiarySdohItemDtoFromJSONTyped(json, false);
}

export function DiarySdohItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiarySdohItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'elementNo': json['elementNo'],
        'majorCat': json['majorCat'] == null ? undefined : json['majorCat'],
        'middleCat': json['middleCat'] == null ? undefined : json['middleCat'],
        'subCat': json['subCat'] == null ? undefined : json['subCat'],
        'signCode': json['signCode'] == null ? undefined : json['signCode'],
        'typeLabel': json['typeLabel'] == null ? undefined : json['typeLabel'],
        'severity': json['severity'] == null ? undefined : json['severity'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'coping': json['coping'] == null ? undefined : json['coping'],
        'recommendation': json['recommendation'] == null ? undefined : json['recommendation'],
        'evidences': json['evidences'],
    };
}

export function DiarySdohItemDtoToJSON(json: any): DiarySdohItemDto {
    return DiarySdohItemDtoToJSONTyped(json, false);
}

export function DiarySdohItemDtoToJSONTyped(value?: DiarySdohItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'elementNo': value['elementNo'],
        'majorCat': value['majorCat'],
        'middleCat': value['middleCat'],
        'subCat': value['subCat'],
        'signCode': value['signCode'],
        'typeLabel': value['typeLabel'],
        'severity': value['severity'],
        'duration': value['duration'],
        'coping': value['coping'],
        'recommendation': value['recommendation'],
        'evidences': value['evidences'],
    };
}

