/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 일기 키워드 정보
 * @export
 * @interface DiaryKeywordDto
 */
export interface DiaryKeywordDto {
    /**
     * 키워드 추출 ID
     * @type {number}
     * @memberof DiaryKeywordDto
     */
    keywordExtractionId: number;
    /**
     * 키워드 그룹 (LIFE_CYCLE: 생애주기, HOUSEHOLD_STATUS: 가구상황, INTERESTS: 관심사)
     * @type {string}
     * @memberof DiaryKeywordDto
     */
    keywordGroup: DiaryKeywordDtoKeywordGroupEnum;
    /**
     * 키워드
     * @type {string}
     * @memberof DiaryKeywordDto
     */
    keyword: string;
    /**
     * 키워드 코드
     * @type {string}
     * @memberof DiaryKeywordDto
     */
    keywordCode?: string;
    /**
     * 키워드 추출 근거 문장 목록
     * @type {Array<string>}
     * @memberof DiaryKeywordDto
     */
    evidences: Array<string>;
}


/**
 * @export
 */
export const DiaryKeywordDtoKeywordGroupEnum = {
    LifeCycle: 'LIFE_CYCLE',
    HouseholdStatus: 'HOUSEHOLD_STATUS',
    Interests: 'INTERESTS'
} as const;
export type DiaryKeywordDtoKeywordGroupEnum = typeof DiaryKeywordDtoKeywordGroupEnum[keyof typeof DiaryKeywordDtoKeywordGroupEnum];


/**
 * Check if a given object implements the DiaryKeywordDto interface.
 */
export function instanceOfDiaryKeywordDto(value: object): value is DiaryKeywordDto {
    if (!('keywordExtractionId' in value) || value['keywordExtractionId'] === undefined) return false;
    if (!('keywordGroup' in value) || value['keywordGroup'] === undefined) return false;
    if (!('keyword' in value) || value['keyword'] === undefined) return false;
    if (!('evidences' in value) || value['evidences'] === undefined) return false;
    return true;
}

export function DiaryKeywordDtoFromJSON(json: any): DiaryKeywordDto {
    return DiaryKeywordDtoFromJSONTyped(json, false);
}

export function DiaryKeywordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiaryKeywordDto {
    if (json == null) {
        return json;
    }
    return {
        
        'keywordExtractionId': json['keywordExtractionId'],
        'keywordGroup': json['keywordGroup'],
        'keyword': json['keyword'],
        'keywordCode': json['keywordCode'] == null ? undefined : json['keywordCode'],
        'evidences': json['evidences'],
    };
}

export function DiaryKeywordDtoToJSON(json: any): DiaryKeywordDto {
    return DiaryKeywordDtoToJSONTyped(json, false);
}

export function DiaryKeywordDtoToJSONTyped(value?: DiaryKeywordDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keywordExtractionId': value['keywordExtractionId'],
        'keywordGroup': value['keywordGroup'],
        'keyword': value['keyword'],
        'keywordCode': value['keywordCode'],
        'evidences': value['evidences'],
    };
}

