/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 일기 복지 서비스 정보
 * @export
 * @interface DiaryWelfareServiceDto
 */
export interface DiaryWelfareServiceDto {
    /**
     * 복지 서비스 ID
     * @type {number}
     * @memberof DiaryWelfareServiceDto
     */
    welfareServiceId: number;
    /**
     * 서비스 범위 (CENTRAL: 중앙정부, LOCAL: 지방정부)
     * @type {string}
     * @memberof DiaryWelfareServiceDto
     */
    serviceScope: DiaryWelfareServiceDtoServiceScopeEnum;
    /**
     * 서비스 고유 ID
     * @type {string}
     * @memberof DiaryWelfareServiceDto
     */
    serviceId: string;
    /**
     * 서비스명
     * @type {string}
     * @memberof DiaryWelfareServiceDto
     */
    serviceName: string;
    /**
     * 서비스 상세 링크
     * @type {string}
     * @memberof DiaryWelfareServiceDto
     */
    serviceDetailLink: string;
    /**
     * 서비스 요약 설명
     * @type {string}
     * @memberof DiaryWelfareServiceDto
     */
    serviceDigest?: string;
    /**
     * 행정구역 1단계 (시/도)
     * @type {string}
     * @memberof DiaryWelfareServiceDto
     */
    adminLevel1Name?: string;
    /**
     * 행정구역 2단계 (시/군/구)
     * @type {string}
     * @memberof DiaryWelfareServiceDto
     */
    adminLevel2Name?: string;
    /**
     * 매칭된 생애주기 키워드 목록
     * @type {Array<string>}
     * @memberof DiaryWelfareServiceDto
     */
    matchedLifeCycleKeywords: Array<string>;
    /**
     * 매칭된 가구상황 키워드 목록
     * @type {Array<string>}
     * @memberof DiaryWelfareServiceDto
     */
    matchedHouseholdStatusKeywords: Array<string>;
    /**
     * 매칭된 관심사 키워드 목록
     * @type {Array<string>}
     * @memberof DiaryWelfareServiceDto
     */
    matchedInterestKeywords: Array<string>;
    /**
     * 사용자에게 표시 여부
     * @type {boolean}
     * @memberof DiaryWelfareServiceDto
     */
    visible: boolean;
}


/**
 * @export
 */
export const DiaryWelfareServiceDtoServiceScopeEnum = {
    Local: 'LOCAL',
    National: 'NATIONAL'
} as const;
export type DiaryWelfareServiceDtoServiceScopeEnum = typeof DiaryWelfareServiceDtoServiceScopeEnum[keyof typeof DiaryWelfareServiceDtoServiceScopeEnum];


/**
 * Check if a given object implements the DiaryWelfareServiceDto interface.
 */
export function instanceOfDiaryWelfareServiceDto(value: object): value is DiaryWelfareServiceDto {
    if (!('welfareServiceId' in value) || value['welfareServiceId'] === undefined) return false;
    if (!('serviceScope' in value) || value['serviceScope'] === undefined) return false;
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('serviceName' in value) || value['serviceName'] === undefined) return false;
    if (!('serviceDetailLink' in value) || value['serviceDetailLink'] === undefined) return false;
    if (!('matchedLifeCycleKeywords' in value) || value['matchedLifeCycleKeywords'] === undefined) return false;
    if (!('matchedHouseholdStatusKeywords' in value) || value['matchedHouseholdStatusKeywords'] === undefined) return false;
    if (!('matchedInterestKeywords' in value) || value['matchedInterestKeywords'] === undefined) return false;
    if (!('visible' in value) || value['visible'] === undefined) return false;
    return true;
}

export function DiaryWelfareServiceDtoFromJSON(json: any): DiaryWelfareServiceDto {
    return DiaryWelfareServiceDtoFromJSONTyped(json, false);
}

export function DiaryWelfareServiceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiaryWelfareServiceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'welfareServiceId': json['welfareServiceId'],
        'serviceScope': json['serviceScope'],
        'serviceId': json['serviceId'],
        'serviceName': json['serviceName'],
        'serviceDetailLink': json['serviceDetailLink'],
        'serviceDigest': json['serviceDigest'] == null ? undefined : json['serviceDigest'],
        'adminLevel1Name': json['adminLevel1Name'] == null ? undefined : json['adminLevel1Name'],
        'adminLevel2Name': json['adminLevel2Name'] == null ? undefined : json['adminLevel2Name'],
        'matchedLifeCycleKeywords': json['matchedLifeCycleKeywords'],
        'matchedHouseholdStatusKeywords': json['matchedHouseholdStatusKeywords'],
        'matchedInterestKeywords': json['matchedInterestKeywords'],
        'visible': json['visible'],
    };
}

export function DiaryWelfareServiceDtoToJSON(json: any): DiaryWelfareServiceDto {
    return DiaryWelfareServiceDtoToJSONTyped(json, false);
}

export function DiaryWelfareServiceDtoToJSONTyped(value?: DiaryWelfareServiceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'welfareServiceId': value['welfareServiceId'],
        'serviceScope': value['serviceScope'],
        'serviceId': value['serviceId'],
        'serviceName': value['serviceName'],
        'serviceDetailLink': value['serviceDetailLink'],
        'serviceDigest': value['serviceDigest'],
        'adminLevel1Name': value['adminLevel1Name'],
        'adminLevel2Name': value['adminLevel2Name'],
        'matchedLifeCycleKeywords': value['matchedLifeCycleKeywords'],
        'matchedHouseholdStatusKeywords': value['matchedHouseholdStatusKeywords'],
        'matchedInterestKeywords': value['matchedInterestKeywords'],
        'visible': value['visible'],
    };
}

