/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScaleQuestionItemDto } from './ScaleQuestionItemDto';
import {
    ScaleQuestionItemDtoFromJSON,
    ScaleQuestionItemDtoFromJSONTyped,
    ScaleQuestionItemDtoToJSON,
    ScaleQuestionItemDtoToJSONTyped,
} from './ScaleQuestionItemDto';

/**
 * 척도 질문 결과 정보
 * @export
 * @interface ScaleQuestionResultDto
 */
export interface ScaleQuestionResultDto {
    /**
     * 척도 카테고리 (ANXIETY_DEPRESSION: 불안/우울, ANGER: 분노)
     * @type {string}
     * @memberof ScaleQuestionResultDto
     */
    scaleCategory: ScaleQuestionResultDtoScaleCategoryEnum;
    /**
     * 해당 척도의 총점
     * @type {number}
     * @memberof ScaleQuestionResultDto
     */
    scaleScore: number;
    /**
     * 질문별 응답 목록
     * @type {Array<ScaleQuestionItemDto>}
     * @memberof ScaleQuestionResultDto
     */
    questions: Array<ScaleQuestionItemDto>;
}


/**
 * @export
 */
export const ScaleQuestionResultDtoScaleCategoryEnum = {
    AnxietyDepression: 'ANXIETY_DEPRESSION',
    Anger: 'ANGER'
} as const;
export type ScaleQuestionResultDtoScaleCategoryEnum = typeof ScaleQuestionResultDtoScaleCategoryEnum[keyof typeof ScaleQuestionResultDtoScaleCategoryEnum];


/**
 * Check if a given object implements the ScaleQuestionResultDto interface.
 */
export function instanceOfScaleQuestionResultDto(value: object): value is ScaleQuestionResultDto {
    if (!('scaleCategory' in value) || value['scaleCategory'] === undefined) return false;
    if (!('scaleScore' in value) || value['scaleScore'] === undefined) return false;
    if (!('questions' in value) || value['questions'] === undefined) return false;
    return true;
}

export function ScaleQuestionResultDtoFromJSON(json: any): ScaleQuestionResultDto {
    return ScaleQuestionResultDtoFromJSONTyped(json, false);
}

export function ScaleQuestionResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScaleQuestionResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'scaleCategory': json['scaleCategory'],
        'scaleScore': json['scaleScore'],
        'questions': ((json['questions'] as Array<any>).map(ScaleQuestionItemDtoFromJSON)),
    };
}

export function ScaleQuestionResultDtoToJSON(json: any): ScaleQuestionResultDto {
    return ScaleQuestionResultDtoToJSONTyped(json, false);
}

export function ScaleQuestionResultDtoToJSONTyped(value?: ScaleQuestionResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scaleCategory': value['scaleCategory'],
        'scaleScore': value['scaleScore'],
        'questions': ((value['questions'] as Array<any>).map(ScaleQuestionItemDtoToJSON)),
    };
}

