/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 척도 질문 항목 정보
 * @export
 * @interface ScaleQuestionItemDto
 */
export interface ScaleQuestionItemDto {
    /**
     * 질문 번호
     * @type {number}
     * @memberof ScaleQuestionItemDto
     */
    questionNumber: number;
    /**
     * 질문 내용
     * @type {string}
     * @memberof ScaleQuestionItemDto
     */
    questionText: string;
    /**
     * 선택한 답변
     * @type {string}
     * @memberof ScaleQuestionItemDto
     */
    selectedOption: string;
}

/**
 * Check if a given object implements the ScaleQuestionItemDto interface.
 */
export function instanceOfScaleQuestionItemDto(value: object): value is ScaleQuestionItemDto {
    if (!('questionNumber' in value) || value['questionNumber'] === undefined) return false;
    if (!('questionText' in value) || value['questionText'] === undefined) return false;
    if (!('selectedOption' in value) || value['selectedOption'] === undefined) return false;
    return true;
}

export function ScaleQuestionItemDtoFromJSON(json: any): ScaleQuestionItemDto {
    return ScaleQuestionItemDtoFromJSONTyped(json, false);
}

export function ScaleQuestionItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScaleQuestionItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'questionNumber': json['questionNumber'],
        'questionText': json['questionText'],
        'selectedOption': json['selectedOption'],
    };
}

export function ScaleQuestionItemDtoToJSON(json: any): ScaleQuestionItemDto {
    return ScaleQuestionItemDtoToJSONTyped(json, false);
}

export function ScaleQuestionItemDtoToJSONTyped(value?: ScaleQuestionItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'questionNumber': value['questionNumber'],
        'questionText': value['questionText'],
        'selectedOption': value['selectedOption'],
    };
}

