/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 워드클라우드 단어 항목
 * @export
 * @interface WordCloudItemDto
 */
export interface WordCloudItemDto {
    /**
     * 단어
     * @type {string}
     * @memberof WordCloudItemDto
     */
    word: string;
    /**
     * 등장 횟수
     * @type {number}
     * @memberof WordCloudItemDto
     */
    count: number;
}

/**
 * Check if a given object implements the WordCloudItemDto interface.
 */
export function instanceOfWordCloudItemDto(value: object): value is WordCloudItemDto {
    if (!('word' in value) || value['word'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function WordCloudItemDtoFromJSON(json: any): WordCloudItemDto {
    return WordCloudItemDtoFromJSONTyped(json, false);
}

export function WordCloudItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordCloudItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'word': json['word'],
        'count': json['count'],
    };
}

export function WordCloudItemDtoToJSON(json: any): WordCloudItemDto {
    return WordCloudItemDtoToJSONTyped(json, false);
}

export function WordCloudItemDtoToJSONTyped(value?: WordCloudItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'word': value['word'],
        'count': value['count'],
    };
}

