/* tslint:disable */
/* eslint-disable */
/**
 * CareDiary API
 * 돌봄일기 서비스
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommonResponseAdminUserDetailResponse,
  CommonResponseAdminUserFindAllResponse,
  CommonResponseAdminUserScaleFindAllResponse,
  CommonResponseAdminUserScaleQuestionResultResponse,
} from '../models/index';
import {
    CommonResponseAdminUserDetailResponseFromJSON,
    CommonResponseAdminUserDetailResponseToJSON,
    CommonResponseAdminUserFindAllResponseFromJSON,
    CommonResponseAdminUserFindAllResponseToJSON,
    CommonResponseAdminUserScaleFindAllResponseFromJSON,
    CommonResponseAdminUserScaleFindAllResponseToJSON,
    CommonResponseAdminUserScaleQuestionResultResponseFromJSON,
    CommonResponseAdminUserScaleQuestionResultResponseToJSON,
} from '../models/index';

export interface FindScaleQuestionResultRequest {
    userId: string;
    count: number;
}

export interface FindUserByIdRequest {
    userId: string;
}

export interface FindUserScalesRequest {
    userId: string;
}

/**
 * 
 */
export class AdminUserApi extends runtime.BaseAPI {

    /**
     * 시스템에 등록된 모든 사용자의 목록을 조회합니다.
     * 전체 사용자 목록 조회
     */
    async findAllUsersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseAdminUserFindAllResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/admin/users`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseAdminUserFindAllResponseFromJSON(jsonValue));
    }

    /**
     * 시스템에 등록된 모든 사용자의 목록을 조회합니다.
     * 전체 사용자 목록 조회
     */
    async findAllUsers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseAdminUserFindAllResponse> {
        const response = await this.findAllUsersRaw(initOverrides);
        return await response.value();
    }

    /**
     * 특정 사용자의 특정 회차 척도 질문에 대한 응답 결과를 조회합니다.
     * 사용자 척도 설문 답변 조회
     */
    async findScaleQuestionResultRaw(requestParameters: FindScaleQuestionResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseAdminUserScaleQuestionResultResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling findScaleQuestionResult().'
            );
        }

        if (requestParameters['count'] == null) {
            throw new runtime.RequiredError(
                'count',
                'Required parameter "count" was null or undefined when calling findScaleQuestionResult().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/admin/users/{userId}/scale-questions`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseAdminUserScaleQuestionResultResponseFromJSON(jsonValue));
    }

    /**
     * 특정 사용자의 특정 회차 척도 질문에 대한 응답 결과를 조회합니다.
     * 사용자 척도 설문 답변 조회
     */
    async findScaleQuestionResult(requestParameters: FindScaleQuestionResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseAdminUserScaleQuestionResultResponse> {
        const response = await this.findScaleQuestionResultRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 특정 사용자의 상세 정보를 조회합니다.
     * 사용자 상세 조회
     */
    async findUserByIdRaw(requestParameters: FindUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseAdminUserDetailResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling findUserById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/admin/users/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseAdminUserDetailResponseFromJSON(jsonValue));
    }

    /**
     * 특정 사용자의 상세 정보를 조회합니다.
     * 사용자 상세 조회
     */
    async findUserById(requestParameters: FindUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseAdminUserDetailResponse> {
        const response = await this.findUserByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 특정 사용자의 모든 척도 측정 결과를 조회합니다.
     * 사용자 척도 점수 조회
     */
    async findUserScalesRaw(requestParameters: FindUserScalesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseAdminUserScaleFindAllResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling findUserScales().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/admin/users/{userId}/scales`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseAdminUserScaleFindAllResponseFromJSON(jsonValue));
    }

    /**
     * 특정 사용자의 모든 척도 측정 결과를 조회합니다.
     * 사용자 척도 점수 조회
     */
    async findUserScales(requestParameters: FindUserScalesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseAdminUserScaleFindAllResponse> {
        const response = await this.findUserScalesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
